### ISSUE TITLE
Brainstorm alternative course abbreviation names

### ISSUE THREAD

**Issue by signekb** [rostools/git4cats#20]
We have discussed that we might need a different name for the course than `cog-flow`.

**Comment by signekb** [comment]
Potential alternatives which I don't particularly like, but that might help start the brainstorming process: 
- GitCollab
- GoGit / CollabGit / CollaborativeGit
- GitTogether
- GitTeamFlow

**Comment by lwjohnst86** [comment]
If we focus on "team-based collaborative workflows" some ideas are:

- `tbc-flow` (a WoW player would think of TBC :stuck_out_tongue:)
- `tec-flow` (evokes an image of tech)
- `teacow` (a cow having tea?)
- `cote-flow` (either the french word or the english word)

**Comment by signekb** [comment]
Or tbc as in `to be confirmed`? 😛 

`cwg-flow` (collaborative workflow in git)?

**Comment by signekb** [comment]
`git-collab-intro`?

**Comment by lwjohnst86** [comment]
The reason I want to avoid `collab` is because it has too much overlap with Google Colab. Same as why we don't call it `git-flow`, since that is already it's own thing.

**Comment by signekb** [comment]
I get why we should avoid `git-flow` bc it's its own thing, but `git-collab` and google colab is not the same? :) At least, I would argue that the similarity isn't big enough to be an issue?

**Comment by lwjohnst86** [comment]
Maybe, but from a "Google-ability"/"search engine" point of view, they are very similar! Google "collab" and the first thing that pops up is Colab :stuck_out_tongue:

**Comment by signekb** [comment]
That's true, but it doesn't show up at all with the search "git collab"?

**Comment by signekb** [comment]
`git teamflow`?

**Comment by lwjohnst86** [comment]
Based on some of the ideas in #40:

- `cat-flow`: (collaboration as a team) also is nice because we can use Cat images and make a link that people are sometimes like cats, hard to get to effectively work together 😛 especially researchers.

**Comment by signekb** [comment]
Ooooo that would be super cute! 🐱 🐈 🐈‍⬛ 
I do still feel the need to have Git as a part of the name though... cat-g? Collaborate as a team with git? And a cool/gangster cat? 🕶️ 🐱 hahah

**Comment by signekb** [comment]
@lwjohnst86 OMG, Git for CATS (**C**oll**A**borate **T**eams) 🐈‍⬛

**Comment by lwjohnst86** [comment]
Or! `git-cats`! Like get cats. Or `cats-git` like "go away cats" 😀

**Comment by signekb** [comment]
I like it 🐈

**Comment by signekb** [comment]
@lwjohnst86 I guess this can be closed with the renaming of the repo?
